TASK LED-ON
TASK LED-OFF

: +LED  32 1 #DIGITALWRITE SYSTEM 25 LED-OFF AFTER ;
: -LED  32 0 #DIGITALWRITE SYSTEM 125 LED-ON AFTER ;

LED-ON RUNS +LED
LED-OFF RUNS -LED

: BOOT 32 1 #PINMODE SYSTEM ;

BOOT

LED-ON NOW
